# Docker
sudo: required
services:
  - docker

language: go
before_install:
  # Golang tools
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/tools/godep
  # Bats (https://github.com/sstephenson/bats), as described in https://blog.engineyard.com/2014/bats-test-command-line-tools
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  # Mock external tools to not fail unit-tests
  - mkdir external-tools
  - echo "#!/bin/bash" > ./external-tools/noop
  - cp ./external-tools/{noop,aws}
  - cp ./external-tools/{noop,knife}
  - cp ./external-tools/{noop,csshx}
  - cp ./external-tools/{noop,tmux-cssh}
  - chmod +x ./external-tools/*

script:
    - COVERALLS='-service travis-ci' PATH="./external-tools:$PATH" ./test.sh
