source 'https://rubygems.org'

gem 'chef' , '<11'
gem 'knife-spork', '<1.3'
gem 'app_config'
gem 'foodcritic'
gem 'knife-ec2'
gem 'knife-file'
gem 'hipchat'
gem 'knife-windows'
gem 'aws-sdk'

group :development do
  gem 'rspec'
end
